### ISSUE TITLE
Configuration Properties for OTel Resource Attributes

### ISSUE THREAD

**Issue by kschlesselmann** [spring-projects-experimental/spring-cloud-sleuth-otel#107]
Hi!

Currently we have a look at Sleuth OTel and it seems the only way to configure resource attributes is by providing a custom `Supplier<io.opentelemetry.sdk.resources.Resource>` like
```kotlin
@Configuration
class SpringCloudSleuthOtelConfiguration {
    @Bean
    fun otelResourceAttributes(): Supplier<Resource> = Supplier {
        Resource.builder()
            .put(ResourceAttributes.DEPLOYMENT_ENVIRONMENT, "local")
            .put(ResourceAttributes.SERVICE_VERSION, "1.0.0")
            .put(ResourceAttributes.SERVICE_NAMESPACE, "my-namespace")
            .build()
    }
}
```

It would be great if the starter could take care of that via configuration properties. I thought of something like
```yaml
spring:
  sleuth:
    otel:
      resource:
        deployment.environment: develop
        service.version: 1.0.0
        …
```
