### ISSUE TITLE
Issues with tags creation and Slf4j’s MDC using local-fields

### ISSUE THREAD

**Issue by HenriqueLBorges** [spring-projects-experimental/spring-cloud-sleuth-otel#112]
**Describe the bug**
I am trying to create tags for my spans and also set my Slf4j’s MDC using `local-fields` declared on my properties file but it doesn't seem to work. I am already doing this with `remote-fields` and it's working flawlessly. I found a similar [issue 28](https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/issues/28) and updated the dependency to `1.0.0-M6` but it doesn't seem to fix the tag creation and Slf4j’s MDC injection using `local-fields`.

**Sample**
```
sleuth:
    baggage:
      remote-fields: request-id
      local-fields: device-id
      correlation-fields: request-id,device-id
      tag-fields: request-id,device-id
```
` {"timestamp":"2022-06-16T02:22:26.679169301Z","level":"INFO","message":"event produced","service_name":"app","context":{"spanId":"0278ba8ef78d4105","traceId":"ed9e84e9743102dcbabed7d02d95ff4b","request-id":"456733"}}`

**Comment by marcingrzejszczak** [comment]
Do you have a sample that replicates this problem?

**Comment by HenriqueLBorges** [comment]
Hello @marcingrzejszczak 

I created an example [here](https://github.com/HenriqueLBorges/demo-sleuth-otel-app).

**[Application.yml](https://github.com/HenriqueLBorges/demo-sleuth-otel-app/blob/main/src/main/resources/application.yml)**

```
sleuth:
    baggage:
      remote-fields: request-id
      local-fields: device-id
      correlation-fields: request-id,device-id
      tag-fields: request-id,device-id 
```

**[Code](https://github.com/HenriqueLBorges/demo-sleuth-otel-app/blob/main/src/main/java/com/example/demo/DemoSleuthOtelApplication.java)**

```
@SpringBootApplication
public class DemoSleuthOtelApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoSleuthOtelApplication.class, args);
	}

	@RestController
	class DemoSleuthOtel {
		private static final Logger log = LoggerFactory.getLogger(DemoSleuthOtelApplication.class);

		@RequestMapping("/test")
		public String service4MethodInController() throws InterruptedException {
			// MDC.put("first", "Dorothy"); -> Works
			log.debug("test endpoint called");
			return "Ok";
		}
	}

}
```

**Request**
```
curl --location --request GET 'http://localhost:18888/test' \
    --header 'request-id: 123' \
    --header 'device-id: 321'
```

**Logs**

<img width="1703" alt="image" src="https://user-images.githubusercontent.com/20938097/174638031-00c153d4-96f8-4cb8-934c-69eeb9353dbc.png">

**Jaeger**

![Captura de Tela 2022-06-20 às 12 42 22](https://user-images.githubusercontent.com/20938097/174637802-127a89a7-d807-493e-83d9-463ebcac4aa1.png)
