### ISSUE TITLE
Provide support to Otel Metrics exporter

### ISSUE THREAD

**Issue by anuragk-sportsbet** [spring-projects-experimental/spring-cloud-sleuth-otel#123]
**Is your feature request related to a problem? Please describe.**
Currently the library does not support sending of OTLP metrics via the https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-exporter-otlp-metrics library

**Describe the solution you'd like**
In order to send traces, the library offers the dependencies with the config
```
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://localhost:4317
          timeout: 30000
```

An enhancement could be to extend it to include metrics as well

```
otel:
  exporter:
    otlp:
      metrics:
         endpoint: http://localhost:4317
         timeout: 30000
```
